CREATE TABLE IF NOT EXISTS "PRODUCTS" (
    "RAW_ID" BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    "TITLE" VARCHAR(50) NOT NULL,
    "PRICE" DOUBLE DEFAULT 0.0);
INSERT INTO "PRODUCTS" VALUES(1, 'Blue Pen', 5.45) ON DUPLICATE KEY UPDATE TITLE=VALUES("TITLE"), PRICE=VALUES("PRICE");
INSERT INTO "PRODUCTS" VALUES(2, 'Red Pen', 5.45) ON DUPLICATE KEY UPDATE TITLE=VALUES("TITLE"), PRICE=VALUES("PRICE");
INSERT INTO "PRODUCTS" VALUES(3, 'Green Pen', 5.45) ON DUPLICATE KEY UPDATE TITLE=VALUES("TITLE"), PRICE=VALUES("PRICE");
INSERT INTO "PRODUCTS" VALUES(4, 'Pencils Box', 20.0) ON DUPLICATE KEY UPDATE TITLE=VALUES("TITLE"), PRICE=VALUES("PRICE");
INSERT INTO "PRODUCTS" VALUES(5, 'Paper Block', 10.25) ON DUPLICATE KEY UPDATE TITLE=VALUES("TITLE"), PRICE=VALUES("PRICE");
INSERT INTO "PRODUCTS" VALUES(6, 'Notebook', 3.15) ON DUPLICATE KEY UPDATE TITLE=VALUES("TITLE"), PRICE=VALUES("PRICE");
INSERT INTO "PRODUCTS" VALUES(7, 'Notebook', 3.15) ON DUPLICATE KEY UPDATE TITLE=VALUES("TITLE"), PRICE=VALUES("PRICE");
INSERT INTO "PRODUCTS" VALUES(8, 'Notebook', 2.95) ON DUPLICATE KEY UPDATE TITLE=VALUES("TITLE"), PRICE=VALUES("PRICE");
INSERT INTO "PRODUCTS" VALUES(9, 'Notebook', 2.85) ON DUPLICATE KEY UPDATE TITLE=VALUES("TITLE"), PRICE=VALUES("PRICE");
INSERT INTO "PRODUCTS" VALUES(10, 'Notebook', 4.0) ON DUPLICATE KEY UPDATE TITLE=VALUES("TITLE"), PRICE=VALUES("PRICE");
INSERT INTO "PRODUCTS" VALUES(11, 'Scratchpad', 2.15) ON DUPLICATE KEY UPDATE TITLE=VALUES("TITLE"), PRICE=VALUES("PRICE");
INSERT INTO "PRODUCTS" VALUES(12, 'Scratchpad', 2.15) ON DUPLICATE KEY UPDATE TITLE=VALUES("TITLE"), PRICE=VALUES("PRICE");
INSERT INTO "PRODUCTS" VALUES(13, 'Scratchpad', 2.2) ON DUPLICATE KEY UPDATE TITLE=VALUES("TITLE"), PRICE=VALUES("PRICE");
INSERT INTO "PRODUCTS" VALUES(14, 'Scotch tape', 1.25) ON DUPLICATE KEY UPDATE TITLE=VALUES("TITLE"), PRICE=VALUES("PRICE");
INSERT INTO "PRODUCTS" VALUES(15, 'Scotch tape', 1.75) ON DUPLICATE KEY UPDATE TITLE=VALUES("TITLE"), PRICE=VALUES("PRICE");
INSERT INTO "PRODUCTS" VALUES(16, 'Scotch tape', 2.25) ON DUPLICATE KEY UPDATE TITLE=VALUES("TITLE"), PRICE=VALUES("PRICE");
INSERT INTO "PRODUCTS" VALUES(17, 'Scotch tape', 4.5) ON DUPLICATE KEY UPDATE TITLE=VALUES("TITLE"), PRICE=VALUES("PRICE");
INSERT INTO "PRODUCTS" VALUES(18, 'Paints', 3.0) ON DUPLICATE KEY UPDATE TITLE=VALUES("TITLE"), PRICE=VALUES("PRICE");
INSERT INTO "PRODUCTS" VALUES(19, 'Paints', 3.55) ON DUPLICATE KEY UPDATE TITLE=VALUES("TITLE"), PRICE=VALUES("PRICE");
INSERT INTO "PRODUCTS" VALUES(20, 'Paints', 4.5) ON DUPLICATE KEY UPDATE TITLE=VALUES("TITLE"), PRICE=VALUES("PRICE");
INSERT INTO "PRODUCTS" VALUES(21, 'Paints', 5.25) ON DUPLICATE KEY UPDATE TITLE=VALUES("TITLE"), PRICE=VALUES("PRICE");
INSERT INTO "PRODUCTS" VALUES(22, 'Paints', 6.15) ON DUPLICATE KEY UPDATE TITLE=VALUES("TITLE"), PRICE=VALUES("PRICE");
INSERT INTO "PRODUCTS" VALUES(23, 'Set of pens', 12.45) ON DUPLICATE KEY UPDATE TITLE=VALUES("TITLE"), PRICE=VALUES("PRICE");
INSERT INTO "PRODUCTS" VALUES(24, 'Set of pens', 13.15) ON DUPLICATE KEY UPDATE TITLE=VALUES("TITLE"), PRICE=VALUES("PRICE");
INSERT INTO "PRODUCTS" VALUES(25, 'Set of pens', 13.5) ON DUPLICATE KEY UPDATE TITLE=VALUES("TITLE"), PRICE=VALUES("PRICE");
INSERT INTO "PRODUCTS" VALUES(26, 'Set of pens', 13.8) ON DUPLICATE KEY UPDATE TITLE=VALUES("TITLE"), PRICE=VALUES("PRICE");
INSERT INTO "PRODUCTS" VALUES(27, 'Ruler', 1.45) ON DUPLICATE KEY UPDATE TITLE=VALUES("TITLE"), PRICE=VALUES("PRICE");
INSERT INTO "PRODUCTS" VALUES(28, 'Ruler', 1.5) ON DUPLICATE KEY UPDATE TITLE=VALUES("TITLE"), PRICE=VALUES("PRICE");
INSERT INTO "PRODUCTS" VALUES(29, 'Ruler', 2.0) ON DUPLICATE KEY UPDATE TITLE=VALUES("TITLE"), PRICE=VALUES("PRICE");
INSERT INTO "PRODUCTS" VALUES(30, 'Ruler', 2.45) ON DUPLICATE KEY UPDATE TITLE=VALUES("TITLE"), PRICE=VALUES("PRICE");

CREATE TABLE IF NOT EXISTS "USERS" (
    "RAW_ID" BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    "NAME" VARCHAR(50) NOT NULL);
INSERT INTO "USERS" VALUES(1, 'Jhon') ON DUPLICATE KEY UPDATE NAME=VALUES("NAME");
INSERT INTO "USERS" VALUES(2, 'Jack') ON DUPLICATE KEY UPDATE NAME=VALUES("NAME");
INSERT INTO "USERS" VALUES(3, 'Bob') ON DUPLICATE KEY UPDATE NAME=VALUES("NAME");
INSERT INTO "USERS" VALUES(4, 'Mateo') ON DUPLICATE KEY UPDATE NAME=VALUES("NAME");
INSERT INTO "USERS" VALUES(5, 'July') ON DUPLICATE KEY UPDATE NAME=VALUES("NAME");

CREATE TABLE IF NOT EXISTS "USERS_PRODUCTS" (
    "RAW_ID" BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    "USER_ID" BIGINT NOT NULL,
    "PRODUCT_ID" BIGINT NOT NULL,
    "PRICE" DOUBLE DEFAULT 0.0,
    CONSTRAINT FK_USER_ID FOREIGN KEY ("USER_ID") REFERENCES USERS("RAW_ID"),
    CONSTRAINT FK_PRODUCT_ID FOREIGN KEY ("PRODUCT_ID") REFERENCES PRODUCTS("RAW_ID"));